language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=b9d340bef3f3f1807c2c5e3a739558593c6faae7d98be07b4257b9fd43362ba7
    - SAUCE_USERNAME=nomego
    - secure: Cq9mduOYPHzJz6e1akWScUvOlI7Nbdu/HmcKdPGJdHIpi2oBuQo0WEyFvYoLALkedt45LCiA7HUraLQndDx1jTkLwyhyu+wQPlTjFEYrb5G/JpqB+61v+ewblA0tZfb59RZslEac/tpdOPURLqQceBZLKArGqPfz+Te/eyBR4rzqX4n7hSmuyQtZf97ncdTMazGTy5tpMvnt4ncWYk8UPTzj3qqY2xbwmaj/E2TIFOGjBs2MVson5UPDUM4oyN2YRcYiy3lpqQeucppf+v3SnjwPh8fbDpwVyVPA2Z6/e8oyeF+XZiZdq+s0zjGV5V3j/TBL+/SyiIJULtFqLhK/m770LnGUJusf300w6LB0mptZZlJt+M327Qo5XhuPvCX1Pc+gASm4kc7kb6LAdIFyZKx0rYxO2B55Rf1yd3SgBRA2QNdKzp6Ep0WEf3d714KEDwe2QOefO6iAn+wUkYk+7/y6vnrR4jUWppjZ9xMG6e7V2fghkQnGR6WfBYOOzXQWmaJV98b7D1NmsdnfwvjsH1NdgB4ombBA2YwiApEH4Mc+3G0gnwkaMofqfYhb3cORWGImfm4KuSOXzXw9/BynQ/JUJUzgh2DHnm+KrVgaCrWH5BvZPx3Nbnw8m25gZZbLo2dcrWGuMTF5jX4fVyCZ03uKrpNpOAcF1cP0XmS08yY=
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - bower_components-1.x
    - ".eslintcache"
    - "$HOME/.cache/bower"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn run lint
script:
  - yarn test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: tnIhDZsHA/PZcXASCkLJv06FYA3phif/RZ+uFTXE8NVetoIGK8xPcR/tZRt5OwWCl1SSjwdcc4NBmT8m7k7zZj/uh1IZwRtIbvWqe+ZlRfjM9OacdhYtsyQ0C0H9h8/hzdeEZ4EgK7m0QtfthKy+KEeaxY+Hua+gvSlUKqdYGX7yCOmZPFZqrcrJ5qEsM4sNi3BO9L0OMQkNNhwwu5F2d/8WTu/rox+IFjobldI6NWlu5hpQpqNcdhyuNBLJ3QazYpPWURr16JZ0xoyvo+chtXpJ4DHMQu1xzzHl5/34gNiQTvblzCpvBJ05J4kXa/HckYy31YidyLgTL9sCFyR/FJMtqyDmnYjIvoIpB1XviSwgRt4cjVo6zLY1BsQR0B0zpAQr2B6PQ2nuh42kxMndo5Bx07/wlR/pWk2CiDc/YlSMH9vO+So2QCpaT7YyxwiRXl0PyKVuBcq/azzXkgavRqN1AsX0VPvcpooAUXyMGugR2U8O4n5dZPz7EaNyXQ7kapmUsjcTVoEPLtibv/2tzRiS0n+jScbwrE8OIRAPFF8A00qCCmJqJzNHkWOw5kTDJsfXTHCbuYa+PtbMdmsuCPksJWxZchHO2twIqIYVMC49XJw/j7Ztpph/cppojlqKkv82URvXz9TLvSdkSZFXGvEh/7lk4ifO6crQJqlahAc=
